DROP TABLE `testing`.`Auth`;
CREATE TABLE IF NOT EXISTS Auth (
    userName VARCHAR(50) NOT NULL,
    userMail VARCHAR(50) NOT NULL PRIMARY KEY,
    userAccess VARCHAR(65) NOT NULL,
    userPassword VARCHAR(65) NOT NULL,
    IsActive BOOL NOT NULL
)  ENGINE=INNODB;